name: Build Golang

on:
  push:

jobs:
  build:
    runs-on: goland:1.23.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependecies
        run: go get .
      - name: Run tests
        run: go test ./...
      - name: Build binary
        run: go build -o lecture-cicd-go-app ./main.go

